version: "3"
services:
  db:
    image: postgres:10.5-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: slotuser
      POSTGRES_PASSWORD: thisishowwedo
  server:
    restart: always
    build: slotmachineserver
    volumes:
      - ./slotmachineserver:/code
    stdin_open: true
    tty: true
    command: /bin/sh
    # ^^^ command for development
    #command: /bin/sh start.bat
    # ^^^ command for running the server
    depends_on:
      - db
    ports:
      - "0.0.0.0:8000:8000"