# Generated by Django 2.1.4 on 2018-12-22 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMachinePlay',
            fields=[
                ('play_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=3)),
                ('payout', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
